// flow-typed signature: 54ec052b55e1a8756b800e920dcab597
// flow-typed version: <<STUB>>/getstorybook_v^1.7.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'getstorybook'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'getstorybook' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'getstorybook/bin/generate' {
  declare module.exports: any;
}

declare module 'getstorybook/generators/METEOR/index' {
  declare module.exports: any;
}

declare module 'getstorybook/generators/REACT_NATIVE/index' {
  declare module.exports: any;
}

declare module 'getstorybook/generators/REACT_NATIVE/template/storybook/addons' {
  declare module.exports: any;
}

declare module 'getstorybook/generators/REACT_NATIVE/template/storybook/index.android' {
  declare module.exports: any;
}

declare module 'getstorybook/generators/REACT_NATIVE/template/storybook/index.ios' {
  declare module.exports: any;
}

declare module 'getstorybook/generators/REACT_NATIVE/template/storybook/stories/Button/index.android' {
  declare module.exports: any;
}

declare module 'getstorybook/generators/REACT_NATIVE/template/storybook/stories/Button/index.ios' {
  declare module.exports: any;
}

declare module 'getstorybook/generators/REACT_NATIVE/template/storybook/stories/CenterView/index' {
  declare module.exports: any;
}

declare module 'getstorybook/generators/REACT_NATIVE/template/storybook/stories/CenterView/style' {
  declare module.exports: any;
}

declare module 'getstorybook/generators/REACT_NATIVE/template/storybook/stories/index' {
  declare module.exports: any;
}

declare module 'getstorybook/generators/REACT_NATIVE/template/storybook/stories/Welcome/index' {
  declare module.exports: any;
}

declare module 'getstorybook/generators/REACT_SCRIPTS/index' {
  declare module.exports: any;
}

declare module 'getstorybook/generators/REACT_SCRIPTS/template/src/stories/Button' {
  declare module.exports: any;
}

declare module 'getstorybook/generators/REACT_SCRIPTS/template/src/stories/index' {
  declare module.exports: any;
}

declare module 'getstorybook/generators/REACT_SCRIPTS/template/src/stories/Welcome' {
  declare module.exports: any;
}

declare module 'getstorybook/generators/REACT/index' {
  declare module.exports: any;
}

declare module 'getstorybook/generators/REACT/template/stories/Button' {
  declare module.exports: any;
}

declare module 'getstorybook/generators/REACT/template/stories/index' {
  declare module.exports: any;
}

declare module 'getstorybook/generators/REACT/template/stories/Welcome' {
  declare module.exports: any;
}

declare module 'getstorybook/generators/WEBPACK_REACT/index' {
  declare module.exports: any;
}

declare module 'getstorybook/generators/WEBPACK_REACT/template/stories/Button' {
  declare module.exports: any;
}

declare module 'getstorybook/generators/WEBPACK_REACT/template/stories/index' {
  declare module.exports: any;
}

declare module 'getstorybook/generators/WEBPACK_REACT/template/stories/Welcome' {
  declare module.exports: any;
}

declare module 'getstorybook/lib/detect' {
  declare module.exports: any;
}

declare module 'getstorybook/lib/has_yarn' {
  declare module.exports: any;
}

declare module 'getstorybook/lib/helpers' {
  declare module.exports: any;
}

declare module 'getstorybook/lib/project_types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'getstorybook/bin/generate.js' {
  declare module.exports: $Exports<'getstorybook/bin/generate'>;
}
declare module 'getstorybook/generators/METEOR/index.js' {
  declare module.exports: $Exports<'getstorybook/generators/METEOR/index'>;
}
declare module 'getstorybook/generators/REACT_NATIVE/index.js' {
  declare module.exports: $Exports<'getstorybook/generators/REACT_NATIVE/index'>;
}
declare module 'getstorybook/generators/REACT_NATIVE/template/storybook/addons.js' {
  declare module.exports: $Exports<'getstorybook/generators/REACT_NATIVE/template/storybook/addons'>;
}
declare module 'getstorybook/generators/REACT_NATIVE/template/storybook/index.android.js' {
  declare module.exports: $Exports<'getstorybook/generators/REACT_NATIVE/template/storybook/index.android'>;
}
declare module 'getstorybook/generators/REACT_NATIVE/template/storybook/index.ios.js' {
  declare module.exports: $Exports<'getstorybook/generators/REACT_NATIVE/template/storybook/index.ios'>;
}
declare module 'getstorybook/generators/REACT_NATIVE/template/storybook/stories/Button/index.android.js' {
  declare module.exports: $Exports<'getstorybook/generators/REACT_NATIVE/template/storybook/stories/Button/index.android'>;
}
declare module 'getstorybook/generators/REACT_NATIVE/template/storybook/stories/Button/index.ios.js' {
  declare module.exports: $Exports<'getstorybook/generators/REACT_NATIVE/template/storybook/stories/Button/index.ios'>;
}
declare module 'getstorybook/generators/REACT_NATIVE/template/storybook/stories/CenterView/index.js' {
  declare module.exports: $Exports<'getstorybook/generators/REACT_NATIVE/template/storybook/stories/CenterView/index'>;
}
declare module 'getstorybook/generators/REACT_NATIVE/template/storybook/stories/CenterView/style.js' {
  declare module.exports: $Exports<'getstorybook/generators/REACT_NATIVE/template/storybook/stories/CenterView/style'>;
}
declare module 'getstorybook/generators/REACT_NATIVE/template/storybook/stories/index.js' {
  declare module.exports: $Exports<'getstorybook/generators/REACT_NATIVE/template/storybook/stories/index'>;
}
declare module 'getstorybook/generators/REACT_NATIVE/template/storybook/stories/Welcome/index.js' {
  declare module.exports: $Exports<'getstorybook/generators/REACT_NATIVE/template/storybook/stories/Welcome/index'>;
}
declare module 'getstorybook/generators/REACT_SCRIPTS/index.js' {
  declare module.exports: $Exports<'getstorybook/generators/REACT_SCRIPTS/index'>;
}
declare module 'getstorybook/generators/REACT_SCRIPTS/template/src/stories/Button.js' {
  declare module.exports: $Exports<'getstorybook/generators/REACT_SCRIPTS/template/src/stories/Button'>;
}
declare module 'getstorybook/generators/REACT_SCRIPTS/template/src/stories/index.js' {
  declare module.exports: $Exports<'getstorybook/generators/REACT_SCRIPTS/template/src/stories/index'>;
}
declare module 'getstorybook/generators/REACT_SCRIPTS/template/src/stories/Welcome.js' {
  declare module.exports: $Exports<'getstorybook/generators/REACT_SCRIPTS/template/src/stories/Welcome'>;
}
declare module 'getstorybook/generators/REACT/index.js' {
  declare module.exports: $Exports<'getstorybook/generators/REACT/index'>;
}
declare module 'getstorybook/generators/REACT/template/stories/Button.js' {
  declare module.exports: $Exports<'getstorybook/generators/REACT/template/stories/Button'>;
}
declare module 'getstorybook/generators/REACT/template/stories/index.js' {
  declare module.exports: $Exports<'getstorybook/generators/REACT/template/stories/index'>;
}
declare module 'getstorybook/generators/REACT/template/stories/Welcome.js' {
  declare module.exports: $Exports<'getstorybook/generators/REACT/template/stories/Welcome'>;
}
declare module 'getstorybook/generators/WEBPACK_REACT/index.js' {
  declare module.exports: $Exports<'getstorybook/generators/WEBPACK_REACT/index'>;
}
declare module 'getstorybook/generators/WEBPACK_REACT/template/stories/Button.js' {
  declare module.exports: $Exports<'getstorybook/generators/WEBPACK_REACT/template/stories/Button'>;
}
declare module 'getstorybook/generators/WEBPACK_REACT/template/stories/index.js' {
  declare module.exports: $Exports<'getstorybook/generators/WEBPACK_REACT/template/stories/index'>;
}
declare module 'getstorybook/generators/WEBPACK_REACT/template/stories/Welcome.js' {
  declare module.exports: $Exports<'getstorybook/generators/WEBPACK_REACT/template/stories/Welcome'>;
}
declare module 'getstorybook/lib/detect.js' {
  declare module.exports: $Exports<'getstorybook/lib/detect'>;
}
declare module 'getstorybook/lib/has_yarn.js' {
  declare module.exports: $Exports<'getstorybook/lib/has_yarn'>;
}
declare module 'getstorybook/lib/helpers.js' {
  declare module.exports: $Exports<'getstorybook/lib/helpers'>;
}
declare module 'getstorybook/lib/project_types.js' {
  declare module.exports: $Exports<'getstorybook/lib/project_types'>;
}
